ALTER TABLE ACCOUNT_CUSTOMER
ADD CONSTRAINT LENGTH_PASSWORD CHECK (LENGTH(DPASSWORD) >= 4),
ADD CONSTRAINT LENGTH_USERNAME CHECK (LENGTH(USERNAME) >= 4);


ALTER TABLE ACCOUNT_EMPLOYEE
ADD CONSTRAINT LENGTH_PASSWORD_EMP CHECK (LENGTH(DPASSWORD) >= 4),
ADD CONSTRAINT LENGTH_USERNAME_EMP CHECK (LENGTH(USERNAME) >= 4);

ALTER TABLE ACCOUNT_EMPLOYEE
DROP CHECK LENGTH_PASSWORD_EMP;

ALTER TABLE ACCOUNT_EMPLOYEE
DROP CHECK LENGTH_USERNAME_EMP;

DROP TABLE SELL;