-- Create Customer Group Table
CREATE TABLE CUSTOMERGROUP (
	NAMEGROUP		VARCHAR(15) 	NOT NULL,
	DEBTTHRESHOLD 	DECIMAL(10,2)	DEFAULT 0,
    
	PRIMARY KEY (NAMEGROUP)
);

-- Create Customer Table
CREATE TABLE CUSTOMER_ACC (
	USERNAME		VARCHAR(100) 	NOT NULL,
	DPASSWORD		VARCHAR(100) 	NOT NULL,
	FNAME			VARCHAR(15) 	NOT NULL,
	MINIT			CHAR,
	LNAME			VARCHAR(15)		NOT NULL,
	ID				CHAR(15),		
	BIRTHDAY		DATE			NOT NULL,
	ADDRESS			VARCHAR(100)	NOT NULL,	
	SEX				CHAR			NOT NULL,
	PHONENUMBER		INT  			NOT NULL,
	DEBT			DECIMAL(10,2)	DEFAULT 0,
    DEBTTHRESHOLD 	DECIMAL(10,2) 	DEFAULT 0,
    NAMEGROUP		VARCHAR(15),
    
	PRIMARY KEY (ID),
	FOREIGN KEY (NAMEGROUP) REFERENCES CUSTOMERGROUP (NAMEGROUP) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Create Employee Table
CREATE TABLE EMPLOYEE_ACC (
	USERNAME		VARCHAR(100) 	NOT NULL,
	DPASSWORD		VARCHAR(100) 	NOT NULL,
	FNAME			VARCHAR(15) 	NOT NULL,
	MINIT			CHAR,
	LNAME			VARCHAR(15)		NOT NULL,
	ID				CHAR(15),
	BIRTHDAY		DATE			NOT NULL,
	ADDRESS			VARCHAR(100)	NOT NULL,
	SEX				CHAR			NOT NULL,
	SALARY 			DECIMAL(10,2)	DEFAULT 0,
    PHONENUMBER		INT  			NOT NULL,
    MANAGER_ID		CHAR(15),
    
	PRIMARY KEY (ID),
    FOREIGN KEY (MANAGER_ID) 	REFERENCES EMPLOYEE_ACC (ID) ON DELETE SET NULL ON UPDATE CASCADE 
);

-- Create Cashier Table
CREATE TABLE CASHIER (
	ID				CHAR(15),
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) 	REFERENCES EMPLOYEE_ACC (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Driver Table
CREATE TABLE DRIVER (
	ID				CHAR(15),
    
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) 	REFERENCES EMPLOYEE_ACC (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Seller Table
CREATE TABLE SELLER (
	ID				CHAR(15),
    
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) 	REFERENCES EMPLOYEE_ACC (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Imexport Table
CREATE TABLE IMEXPORT (
	ID				CHAR(15),
    
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) 	REFERENCES EMPLOYEE_ACC (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Order Table
CREATE TABLE DORDER (
	ID				CHAR(15),
	NOTE		    TEXT 			NOT NULL,
	SHIPADDRESS		VARCHAR(100)	NOT NULL,
	CREATEDATE		DATE			NOT NULL,
	DSTATUS		    TEXT 	 	  	NOT NULL,
    CUS_ID			CHAR(15),
    SELL_ID			CHAR(15),
    
	PRIMARY KEY (ID),
	FOREIGN KEY (CUS_ID) 		REFERENCES CUSTOMER_ACC (ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (SELL_ID) 		REFERENCES SELLER (ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Create Items Table
CREATE TABLE ITEMS (
	ID				CHAR(15),
	DTYPE			VARCHAR(30)		NOT NULL,
    DDESCRIPTION	TEXT			NOT NULL,
    DNAME			VARCHAR(30)		NOT NULL,
	COLOR			VARCHAR(15),
    RULES			TEXT,
    IMAGES			VARCHAR(100),
    SUPPLIER		VARCHAR(100)	NOT NULL,
	INVENTORY		INT				DEFAULT 0,
    
	PRIMARY KEY (ID)
);

-- Create Bill Table
CREATE TABLE BILL (
	ID				CHAR(15),
	ORDER_ID		CHAR(15),
	SELL_ID			CHAR(15),			
    
	PRIMARY KEY (ID),
	FOREIGN KEY (ORDER_ID) REFERENCES DORDER (ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (SELL_ID) REFERENCES SELLER (ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Create infor Table
CREATE TABLE INFOR (
	QUANTITY		INT				DEFAULT 0,
	UNIT		    VARCHAR(30)		NOT NULL,
	UNITPRICE		DECIMAL(10,2)	DEFAULT 0,
	TAXVAT			DECIMAL(10,2)	DEFAULT 0,
	RELEASEDATE		DATE			NOT NULL,
    BILL_ID			CHAR(15),
    ITEMS_ID		CHAR(15),
    
	PRIMARY KEY (BILL_ID,ITEMS_ID),
	FOREIGN KEY (BILL_ID) 		REFERENCES BILL (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ITEMS_ID) 		REFERENCES ITEMS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Includes Table
CREATE TABLE INCLUDES (
	QUANTITY		INT				DEFAULT 0,
	UNIT		    VARCHAR(30)		NOT NULL,
    ORDER_ID		CHAR(15),
    ITEMS_ID		CHAR(15),
    
	PRIMARY KEY (ORDER_ID,ITEMS_ID),
	FOREIGN KEY (ORDER_ID) 		REFERENCES DORDER (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ITEMS_ID) 		REFERENCES ITEMS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Transport Department Table
CREATE TABLE TRANS_DEPT (
	ID		CHAR(15),
	PRIMARY KEY (ID)
);

-- Create in Transport Unit Internal Table
CREATE TABLE IN_TRANS_DEPT (
	ID				CHAR(15),
    LICENSE			VARCHAR(30)		NOT NULL,
    DRIVER_ID		CHAR(15),
    
	PRIMARY KEY (ID),
    FOREIGN KEY (DRIVER_ID) 		REFERENCES DRIVER (ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (ID) 				REFERENCES TRANS_DEPT (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create ex Transport Department Table
CREATE TABLE EX_TRANS_DEPT (
    FNAME			VARCHAR(15) 	NOT NULL,
	MINIT			CHAR,
	LNAME			VARCHAR(15)		NOT NULL,
	ID				CHAR(15),
	BIRTHDAY		DATE			NOT NULL,
	ADDRESS			VARCHAR(100)	NOT NULL,
	SEX				CHAR			NOT NULL,
	PHONENUMBER		INT  			NOT NULL,
	LICENSE			VARCHAR(30)		NOT NULL,
    
	PRIMARY KEY (ID),
    FOREIGN KEY (ID) 				REFERENCES TRANS_DEPT (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Delivery Table
CREATE TABLE DELIVERY (
	ID				CHAR(15),
	DSTATUS		    TEXT 			NOT NULL,
	DPOSITION		VARCHAR(30)		NOT NULL,
    IMEX_ID			CHAR(15),
    TRANS_ID		CHAR(15),
    
	PRIMARY KEY (ID),
	FOREIGN KEY (IMEX_ID) 		REFERENCES IMEXPORT (ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (TRANS_ID) 		REFERENCES TRANS_DEPT(ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Creat Shiped Table
CREATE TABLE SHIPPED (
	QUANTITY		INT				DEFAULT 0,
	DTIME		    DATE			NOT NULL,
    UNIT			VARCHAR(30)		NOT NULL,
    WEIGHT			FLOAT			DEFAULT 0,
    DEL_ID			CHAR(15),
    ITEMS_ID		CHAR(15),
    ORDER_ID		CHAR(15),
    
	PRIMARY KEY (DEL_ID,ITEMS_ID,ORDER_ID),
	FOREIGN KEY (DEL_ID) 		REFERENCES DELIVERY (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ITEMS_ID) 		REFERENCES ITEMS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ORDER_ID) 		REFERENCES DORDER (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Creat Payment Table
CREATE TABLE PAYMENT (
	ID				CHAR(15),
	DTIME			DATE				NOT NULL,
	AMONEY			DECIMAL(10,2)		DEFAULT 0,
	PURPOSE			VARCHAR(100)		NOT NULL,
	CASH_ID			CHAR(15),
    
	PRIMARY KEY (ID),
    FOREIGN KEY (CASH_ID) 		REFERENCES CASHIER (ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Creat Coupons Table
CREATE TABLE COUPONS (
	ID				CHAR(15),
	DTIME			DATE				NOT NULL,
	AMONEY			DECIMAL(10,2)		DEFAULT 0,
	CASH_ID			CHAR(15),
    CUS_ID			CHAR(15),
    
	PRIMARY KEY (ID),
    FOREIGN KEY (CASH_ID) 		REFERENCES CASHIER (ID) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (CUS_ID) 		REFERENCES CUSTOMER_ACC (ID) ON DELETE SET NULL ON UPDATE CASCADE
);
