DELIMITER $$
CREATE TRIGGER EMPLOYEE_CHECK_BEFORE_INSERT
BEFORE INSERT
ON EMPLOYEE_ACC FOR EACH ROW
BEGIN
	DECLARE _DATE DATE ;
	DECLARE _CDATE DATE ;
	DECLARE _AGE INT ;
	SET _AGE = (SELECT YEAR(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(NEW.BIRTHDAY)))) ;
	SET _DATE = NEW.BIRTHDAY ;
	SET _CDATE =  CURRENT_DATE() ;
    
    IF NOT EXISTS ( SELECT * FROM EMPLOYEE_ACC WHERE ID = NEW.ID) THEN
		IF (_DATE  > _CDATE) THEN
			SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'Birthday is not available . Must be before current date .' ;
		ELSE
			IF (_AGE < 18) THEN
				SIGNAL SQLSTATE '45001'
					SET MESSAGE_TEXT = 'Age of employee must be over 18 or 18 .' ;
		    END	IF ;
	    END IF ;
	ELSE 
		SIGNAL SQLSTATE '45002'
			SET MESSAGE_TEXT = 'That id of employee is taken . Try another . ' ;
	END IF ;

END $$

DELIMITER ;

INSERT INTO EMPLOYEE_ACC 
	VALUES ('idolh44','passwoE','Giang', 'T', 'Pham', '3500025', '2000-03-06', '650 Dallas, Houston, TX', 'M', 500 , 0941292933,'350002');

DROP TRIGGER EMPLOYEE_CHECK_BEFORE_INSERT;


DELIMITER $$
CREATE TRIGGER ITEMS_CHECK_AFTER_INSERT
AFTER INSERT
ON INFOR FOR EACH ROW
BEGIN
	UPDATE ITEMS SET INVENTORY = INVENTORY - NEW.QUANTITY 
				WHERE ID = NEW.ITEMS_ID ;
END$$
DELIMITER ;

INSERT INTO INFOR
VALUES (15, 'm' , '3000', 10000, '2020-9-11','5000004','100000');

DROP TRIGGER ITEMS_CHECK_AFTER_INSERT;


DELIMITER $$

CREATE TRIGGER ITEMS_INVENTORY_UP
BEFORE UPDATE
ON ITEMS FOR EACH ROW
BEGIN
    DECLARE errorMessage VARCHAR(255);
    SET errorMessage = CONCAT('The new inventory ',
                        NEW.INVENTORY,
                        ' cannot be 10 times greater than the current inventory ',
                        OLD.INVENTORY);
                        
    IF new.INVENTORY > old.INVENTORY * 10 THEN
        SIGNAL SQLSTATE '45000' 
            SET MESSAGE_TEXT = errorMessage;
    END IF;
END $$

DELIMITER ;


UPDATE ITEMS 
SET INVENTORY = 150
WHERE ID = '100001';


CREATE TRIGGER EMP_DELETE_DRIVER
AFTER DELETE
ON EMPLOYEE_ACC FOR EACH ROW
DELETE FROM IN_TRANS_DEPT
WHERE DRIVER_ID = OLD.ID;

DELETE FROM EMPLOYEE_ACC
WHERE ID = '350008';
