DELIMITER //
CREATE FUNCTION ADDRESS_CUS (_ID CHAR(15))
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
	DECLARE ADDRESS	VARCHAR(100) ;
    
	IF NOT EXISTS(SELECT * FROM CUSTOMER_ACC WHERE ID = _ID) THEN
		RETURN -1 ;
	END IF ;
    
	SET ADDRESS = (SELECT SHIPADDRESS FROM DORDER WHERE  CUS_ID = _ID) ;
	RETURN ADDRESS ;
END;  //
DELIMITER  ;

DELIMITER //
CREATE FUNCTION DATE_DRIVER (_ID CHAR(15))
RETURNS DATE
DETERMINISTIC
BEGIN
	DECLARE _DATE DATE ;
    DECLARE ID_  CHAR(15) ;
	IF NOT EXISTS(SELECT * FROM IN_TRANS_DEPT WHERE ID = _ID) THEN
		RETURN -1 ;
	END IF ;
    SET ID_ = (SELECT DRIVER_ID FROM IN_TRANS_DEPT WHERE ID = _ID) ;
	SET _DATE = (SELECT BIRTHDAY FROM EMPLOYEE_ACC WHERE ID = ID_) ;
	RETURN _DATE;
END;  //
DELIMITER  ;

SELECT ADDRESS_CUS ('18120001');
DROP FUNCTION ADDRESS_CUS;

SELECT DATE_DRIVER ('9004');
DROP FUNCTION DATE_DRIVER;
